MAINTAINER Selenium <selenium-developers@googlegroups.com>

#========================
# Selenium Configuration
#========================

EXPOSE 4444
EXPOSE 3000

ENV GRID_NEW_SESSION_WAIT_TIMEOUT -1
ENV GRID_JETTY_MAX_THREADS -1
ENV GRID_NODE_POLLING  5000
ENV GRID_CLEAN_UP_CYCLE 5000
ENV GRID_TIMEOUT 30000
ENV GRID_BROWSER_TIMEOUT 0
ENV GRID_MAX_SESSION 5
ENV GRID_UNREGISTER_IF_STILL_DOWN_AFTER 30000

#===========================
# video recording capability
# https://github.com/aimmac23/selenium-video-node/blob/master/INSTALLATION.md
#===========================
RUN apt-get -qqy update && apt-get install -qqy wget
# video extension alongside the hub code
RUN wget http://repo1.maven.org/maven2/com/aimmac23/selenium-video-node/2.1/selenium-video-node-2.1.jar -O /opt/selenium/selenium-video-node-2.1.jar


COPY generate_config /opt/selenium/generate_config
COPY entry_point.sh /opt/bin/entry_point.sh
RUN chown -R seluser /opt/selenium

USER seluser

CMD ["/opt/bin/entry_point.sh"]

